#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username postgres --dbname $POSTGRES_DB <<-EOSQL
    CREATE DATABASE $DATABASE;
    CREATE USER $USER WITH ENCRYPTED PASSWORD '$PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $DATABASE to $USER;
EOSQL

