apiVersion: v1
kind: Service
metadata:
  labels:
    app: oap-db
  name: oap-db
  namespace: dev
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: oap-db
