apiVersion: v1
kind: Service
metadata:
  name: oap-ui
  namespace: dev
  labels:
    app: oap-ui
spec:
  type: NodePort
  ports:
  - port: 8080
    name: port1
    protocol: TCP
    targetPort: 8080
    nodePort: 31200
  selector:
    app: oap-ui

